### ISSUE TITLE
Spurious ci-test-error with trace

### ISSUE THREAD

**Issue by power-fungus** [suhailshergill/extensible-effects#106]
As I understand, The test for `Trace` fails sometimes in different configurations on travis-ci.

See:
* https://travis-ci.org/suhailshergill/extensible-effects/builds/374066261
* https://travis-ci.org/suhailshergill/extensible-effects/builds/374068667

**Comment by suhailshergill** [comment]
@power-fungus yes. the issue is how we test expectations for `Trace` in [its test-suite](https://github.com/suhailshergill/extensible-effects/blob/master/test/Control/Eff/Trace/Test.hs). specifically, via [capturing `stdout`](https://github.com/suhailshergill/extensible-effects/blob/master/test/Utils.hs#L14).

**Comment by power-fungus** [comment]
For some reason, I feel quite strongly about `Trace´. The effect-algebra is strictly weaker than `Writer´, for no particular benefit.

What I would like:
* Add writer functions along the lines (whatever makes most sense, I will tinker with it)
```haskell
runMonadWriter :: (Monad m) => Eff (Writer (m w) ': r) a -> Eff r (a, m [w])
runAlternativeWriter :: (Alternative m) => Eff (Writer w ': r) a -> Eff r (a, m w)
```
* deprecate the `Trace` effect and schedule it for removal in a further release. Note that then, `runTrace` is roughly equivalent to `execMonadWriter putStrLn` (as far as I can tell)

That writer is cabable of tracing can then be documented somewhere.

Then, it is also not necessary to do the impure test and do it with some pure monad instead.

Also, if a logging effect is desired, such an effect can also be implemented, but that should have a richer feature-set.

**Comment by suhailshergill** [comment]
@power-fungus let's leave the purity of the test aside for a moment. for something like tracing and logging, i do want to check that which was logged (as opposed to that which was intended to be logged). given that, i do agree the testing can still be improved, but it's a relatively minor issue for now (albeit, patches are always welcome).

regarding reformulating `Trace` in terms of `Writer`, what's the advantage we get (from a user perspective)?

**Comment by suhailshergill** [comment]
btw, happy to discuss this on gitter (https://gitter.im/suhailshergill/extensible-effects)

**Comment by power-fungus** [comment]
I agree that this is a minor issue and although I have a standpoint, it is not too important.

Advantages:
* Conceptually, trace is a writer. When I fist learned the effects, I did not 
* Using trace in a library would be bad practice anyway as the user of the library has to accept that output is getting cluttered (a possible fix would be to write a runner that ignores the trace)

**Comment by power-fungus** [comment]
see [my commit](https://github.com/power-fungus/extensible-effects/commit/c4131e72cc567a071d3f921da52fe43ad8e9427f) for a quick-and-dirty implementation.

**Comment by power-fungus** [comment]
Closing this issue for now. #108 does *some* workaround, and maybe helps.
