### ISSUE TITLE
RFC: Version semantics

### ISSUE THREAD

**Issue by greydot** [suhailshergill/extensible-effects#122]
How are version numbers assigned in this library? Is this a kind of semantic versioning? If so, then why four numbers and not three?

**Comment by suhailshergill** [comment]
Semantic versioning using cabal defaults I believe. The cabal file
clarifies.

--
Suhail

**Comment by suhailshergill** [comment]
https://github.com/suhailshergill/extensible-effects/blob/develop/extensible-effects.cabal#L6
