### ISSUE TITLE
Decide on: support GHC 8.0 vs use pattern synonyms in implementations

### ISSUE THREAD

**Issue by suhailshergill** [suhailshergill/extensible-effects#126]
#125 (specifically commit 4170021 ) highlights the trade-off. Pattern synonyms help reduce the syntactic noise to a minimum, making it easier to understand the semantics. However, in this case the syntactic noise isn't too much to begin with and arguably 8.0.2 wasn't that far long ago (Jan 2017).

I would like to hear from the community before deciding. Paging: @sheyll , @mattaudesse , @shineli1984 , @power-fungus , @greydot

**Comment by greydot** [comment]
A number of libraries support the latest three ghc releases. I tend to agree with that practice.

That being said, ghc has a new release cycle now with less time between releases.

How about we support the compiler for a limited amount of time? Say, two years should be enough. With that regard, it makes sense to drop ghc 8.0 support in this case.

**Comment by mattaudesse** [comment]
A rolling two-year `ghc` version support window like @greydot suggests sounds reasonable to me but I don't really have a strong opinion.

**Comment by sheyll** [comment]
Thanks for asking; my 2 cents: as long as the user base has not grown past a certain point, I would value library evolution/exploration over compiler compatibility. And since you asked, I would prefer using pattern synonyms to reduce syntactic noise over GHC 8.0.2 compatibility.

**Comment by suhailshergill** [comment]
> oh, btw, isn't PatternSynonyms and ViewPatterns already in GHC 7.x ?

it is, however, the completeness checks weren't adequately implemented yet.

**Comment by suhailshergill** [comment]
thanks, will focus more on cleaner implementation via `PatternSynonyms` and drop support of 8.0.2 in the next few weeks.
have also been investigating #98 to better understand what affects the performance in these effects. I expect to roll some changes relating to these (making it harder for the user to accidentally shoot themselves in the foot wrt performance).
happy holidays!

**Comment by sheyll** [comment]
Sounds great, happy holidays to you, too, and happy hacking :)
