### ISSUE TITLE
Undeclared `TypeApplications` extension

### ISSUE THREAD

**Issue by hvr** [suhailshergill/extensible-effects#130]
This caused failures for GHCs lacking this extension:

```
Configuring library for extensible-effects-5.0.0.1..
Preprocessing library for extensible-effects-5.0.0.1..
Building library for extensible-effects-5.0.0.1..

src/Control/Eff/Logic/NDet.hs:12:14:
    Unsupported extension: TypeApplications
<<ghc: 120132488 bytes, 93 GCs, 2975444/7807312 avg/max bytes residency (5 samples), 16M in use, 0.001 INIT (0.001 elapsed), 0.041 MUT (0.041 elapsed), 0.063 GC (0.063 elapsed) :ghc>>
```

I've already fixed up the metadata for the affected releases (i.e. there's no need to upload a costly release to Hackage -- it's already fixed on Hackage):

- https://hackage.haskell.org/package/extensible-effects-5.0.0.1/revisions
- https://hackage.haskell.org/package/extensible-effects-5.0.0.0/revisions
- https://hackage.haskell.org/package/extensible-effects-4.0.0.0/revisions

You can inspect the current Hackage build-plan health at [![Hackage Matrix CI](https://matrix.hackage.haskell.org/api/v2/packages/extensible-effects/badge)](https://matrix.hackage.haskell.org/package/extensible-effects)

Let me know if you have any questions.

**Comment by suhailshergill** [comment]
@hvr thanks! appreciate the help :)
