### ISSUE TITLE
RFC: Handle class

### ISSUE THREAD

**Issue by greydot** [suhailshergill/extensible-effects#132]
It would be nice to read on the motivation behind this class, as well as have a manual on how to implement effects with it. Right now the latter part is not entirely obvious.

**Comment by suhailshergill** [comment]
@greydot thanks for creating this. i'll take a stab at elaborating the main idea and fleshing out the documentation. i would welcome your review and feedback and hope to get the documentation fleshed out to the point where you are satisfied with the explanation.

**Comment by suhailshergill** [comment]
@greydot let me know your thoughts on 79d99e9

**Comment by greydot** [comment]
@suhailshergill this explains what and how. Could you also add why? I think it was mentioned somewhere that this approach gives performance benefits against the old-style handlers, but it would be nice to have this in docs.

**Comment by suhailshergill** [comment]
Ah, good catch! The "why" is slightly subtler. Shallow handlers are more
flexible/expressive and as such allow us to describe more performant
handlers (which previously required us to manually pattern match on the Eff
data type).
I'll clarify and elaborate on this.

--
Suhail

**Comment by suhailshergill** [comment]
I thought some more about this and I think I can articulate better now what
I meant (current docs aren't quite right). Will push some further
documentation today.
Thank you once again for pushing me for this.

--
Suhail

**Comment by suhailshergill** [comment]
@greydot please have a look and let me know your thoughts

**Comment by greydot** [comment]
@suhailshergill splendid! Thanks. I think I'll start working on the part of the readme about writing new effects some time soon. From what I've been told, this is one of the confusing parts.

**Comment by suhailshergill** [comment]
@greydot perfect, i've assigned #99 to you. thanks!
