### ISSUE TITLE
allow (de)serializing internal Eff r state

### ISSUE THREAD

**Issue by ibotty** [suhailshergill/extensible-effects#16]
i want to interface with wai and generate a `Middleware :: Request -> IO Response` from a `SetMember Lift (Lift IO) r => Request -> Eff r Response`  action.

i looked into what yesod is doing (which for that discussion reduces to having a an action `Request -> ResourceT IO Response`). yesod gets `ResourceT`'s internal state (aptly named `InternalState` and restores it afterwards using functions (specialized to `IO`):

``` haskell
withInternalState :: (InternalState -> IO a) -> ResourceT IO a
createInternalState :: IO InternalState
closeInternalState :: InternalState -> IO ()
```

see the [hackage documentation](https://hackage.haskell.org/package/resourcet-1.1.2.2/docs/Control-Monad-Trans-Resource.html#t:InternalState).

can something similar be done with `Eff r`? can one somehow expose the underlying `VE w r` and will that suffice to reconstruct `Eff r`'s state?

that might also lead to insights regarding the catch and mask semantics i want in my other bug. given that functionality, one could use `runLift` to implement catch with the existing `catch` from Control.Exception. that way one could give an instance for `MonadCatch` and `MonadMask` from `exceptions` **edit**: and more generally for `MonadBaseControl` from `monad-control`.

**Comment by suhailshergill** [comment]
fixed by #83
