### ISSUE TITLE
fix Typeable dependency

### ISSUE THREAD

**Issue by suhailshergill** [suhailshergill/extensible-effects#38]
Integrating http://okmij.org/ftp/Haskell/extensible/OpenUnion4.hs will address this concern

**Comment by fosskers** [comment]
Looking forward to this.

**Comment by suhailshergill** [comment]
@fosskers understand that the `OpenUnion4.hs` implementation above comes at a performance penalty.

also, ooc, could you elaborate on your concerns with current `Typeable` dependency?

**Comment by fosskers** [comment]
Verbose type signatures are my only concern.

**Comment by suhailshergill** [comment]
@fosskers note that with `ConstraintKinds` enabled you could have an alias for the constraints (partial or otherwise) needed in the signatures. that can help limit the type annotation noise in the interim

**Comment by fosskers** [comment]
Neat, I didn't know about `ConstraintKinds`.

**Comment by suhailshergill** [comment]
#56 will fix this

**Comment by suhailshergill** [comment]
duplicate of #56
