### ISSUE TITLE
Incorporate updates from recent paper (i.e. use alternate definition of Free w/o Functor constraint)

### ISSUE THREAD

**Issue by suhailshergill** [suhailshergill/extensible-effects#56]
- [x] port ideas from http://okmij.org/ftp/Haskell/extensible/more.pdf and http://okmij.org/ftp/Haskell/extensible/Eff1.hs to the library
  - [x] make a decision on whether or not to support the different OpenUnion implementations
    - use [`OpenUnion51.hs`](http://okmij.org/ftp/Haskell/extensible/OpenUnion51.hs) implementation
- [x] add [DelayState ("Lazy")](http://okmij.org/ftp/Haskell/extensible/index.html#lazy-state) and possibly other delayed variants
- [ ] release on hackage

the above would address the point regd. Lazy writer and Lazy state effects made by @ekmett in https://www.reddit.com/r/haskell/comments/387ex0/are_extensible_effects_a_complete_replacement_for/crt1pzm as can be seen in code example provided by oleg below:

``` haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE NoMonomorphismRestriction #-}

-- On-demand state computation:
-- example taken from edward kmett's comment here:
-- <http://www.reddit.com/r/haskell/comments/387ex0/are_extensible_effects_a_complete_replacement_for/crt1pzm>

-- The state here is lazy and not extensible: neither it was in ekmett's
-- comments

-- Extensible effects make it clear that where the computation is delayed
-- (which I take as an advantage) and they do maintain the degree of
-- extensibility (the delayed computation must be effect-closed, but the
-- whole computation does not have to be).

module LazyState where

import Eff1
import OpenUnion41


-- define a new effect for state on-demand (in ExtEff, the state is
-- by default strict -- as it should be if we want the predictable performance
-- and effect sequencing)

data LazyState s v where
  Get :: LazyState s s
  Put :: s -> LazyState s ()
  Delay :: Eff '[LazyState s] a  -> LazyState s a --  Eff as a transformer


runStateLazy :: s -> Eff '[LazyState s] a -> Eff '[] (a,s)
runStateLazy s = handle_relay_s s (\s x -> return (x,s))
                   (\s req k -> case req of
                       Get   -> unArr (k s) s
                       Put s -> unArr (k s) ()
                       Delay m -> let ~(x,s1) = run $ runStateLazy s m
                                  in unArr (k s1) x)

lget = send Get
lput = send . Put

onDemand :: Eff '[LazyState s] v -> Eff '[LazyState s] v
onDemand = send . Delay


lex1 = do
  onDemand lex1
  lput (1::Int)

ex1Run :: ((),Int)
ex1Run = run $ runStateLazy 0 lex1
-- ((),1)

-- modify as Delay

lmodify :: (s->s) -> Eff '[LazyState s] ()
lmodify f = onDemand $ do
  s <- lget
  lput (f s)


lex2 = do
  lmodify ((1::Int):)
  lmodify ((2::Int):)
  lget

ex2Run :: ([Int],[Int])
ex2Run = run $ runStateLazy [] lex2
-- ([2,1],[2,1])

-- Edward's example

lex3 = do
  onDemand lex3
  lmodify ((1::Int):)

ex3Run :: ((),[Int])
ex3Run = let (x,s) = run $ runStateLazy [] lex3
         in (x,take 5 s)

-- ((),[1,1,1,1,1])

-- a bit more interesting
lex4 :: Eff '[LazyState [Int]] [Int]
lex4 = do
  onDemand lex4
  lmodify ((1::Int):)
  lmodify ((2::Int):)
  lget

ex4Run :: ([Int],[Int])
ex4Run = let (x,s) = run $ runStateLazy [] lex4
         in (take 7 $ x,take 5 $ s)

-- ([2,1,2,1,2,1,2],[2,1,2,1,2])
```

**Comment by ekmett** [comment]
Clever.

Lazy state and lazy writer compose, no? 

Is there an option for how to make such an explicit Delay/demand based computation model more composable when all of the effect types are demand-drivable?

**Comment by rvion** [comment]
is there any eta on this ?
Having a fast extensible-effects equivalent to `transformers` or `mtl` with proper community advertising  could really start the adoption.

**Comment by suhailshergill** [comment]
I'm aiming for end November, but if you'd like to contribute a patch in the
meanwhile I'll be happy to review.
Retaining the new version of open union (which has order n performance
operations) alongside the old is proving to be tricky however, and that's
where most of the complexity is. Are you running into scenarios at present
where the current implementation isn't satisfactory?

**Comment by suhailshergill** [comment]
@ekmett missed your comment on this previously, my bad. i don't often find myself relying on (or rather i try not to rely on) such delay/demand based computation model, so unfortunately i am out of my depth here. that being said, could you qualify/paint a picture of what you were thinking of/had in mind. i don't believe i fully grasp the scenario you're thinking of.

**Comment by rvion** [comment]
Is the `freer` package superseding the `extensible-effects` package ?
 - ["freer" source on gitlab](https://gitlab.com/cpp.cabrera/freer)
 - ["freer" on hackage](http://hackage.haskell.org/package/freer)
 - ["freer" changelog on hackage](http://hackage.haskell.org/package/freer/changelog)

**Comment by suhailshergill** [comment]
I think it depends on what you need. Freer currently is the package which
has the improvements from the "freer" paper. My goal with
extensible-effects is to continue to support some of the alternate designs
outlined in the previous papers as well but haven't had enough time to
devote to it due to personal reasons. If you want something which
incorporates the newer ideas and works today, it seems like freer fits the
bill.

**Comment by rvion** [comment]
thanks for your quick response :)

**Comment by suhailshergill** [comment]
np :)
ooc, could you elaborate on the capacity to which you're using the ideas of
extensible effects/freer? is it for personal projects? is it from the
perspective of a library user, or more from the perspective of a library
author yourself?

On Tue, Jan 5, 2016 at 4:40 AM, Rémi Vion <notifications@github.com> wrote:

> thanks for your quick response :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/suhailshergill/extensible-effects/issues/56#issuecomment-168948956>
> .
>



-- 
Suhail

**Comment by rvion** [comment]
I'm interested in extensible effects both as a library user and library author, and both for personal and professional projects.

I like the idea of extensible effects because for the simplicity of the concept, the sharability of code blocs, testing facility, the possible variety of interpreters for a same effects, etc. Nothing new here; the raise of extensible effects in idris, purescript, and the the various recent Oleg [articles](http://okmij.org/ftp/Computation/free-monad.html) and [papers](http://okmij.org/ftp/Haskell/extensible/more.pdf) pretty much convinced me to give it an other try. Also, I feel a bit sad to start building libraries on transformers knowing that I'll probably never be able to easilly reuse them.

Speed is not really critical for me, but I'd like to use the new `freer` approch because:
 - I want to see how bad look type errors with the new freer implementation, so I know how newcomer-friendly it is __(this is one of the main reason for me to try the new freer approach)__
 - I hope that some of inference problems I had when playing with extensible-effects will be solved with the new closed type families implementation of data types à la carte
 - I'm happy to think I'm not relying on Typeable and overlapping instances 
 - I'm don't know if I'll really need lazy effects, but I'm hapy to know I'll be able to if I need to.


Also, I'm not really concerned about the interpreters not obeying the monad laws. I think the error surface remains small, and that "cheating" may be fine in some cases.

I know that things will keep moving, maybe open unions will change to use future  overloaded labels or row types, etc. but anyway, I don't want to wait for perfection forever, it may never come :)

**Comment by ocharles** [comment]
The example given doesn't seem to demonstrate any composability. That is, you explicitly choose the effect stack to *just* be state. Is it possible to extend this approach to any arbitrary stack of effects?

**Comment by suhailshergill** [comment]
@ocharles i believe it's possible to have consistent composable semantics between say lazy writer and state (though the above example doesn't demonstrate it). it's not clear to me what the semantics you'd want to ascribe to them.
could you illustrate with an example what you're attempting to accomplish?

**Comment by ocharles** [comment]
I'm afraid I have no example, I'm not trying to do anything (I don't use `extensible-effects`) - I'm just interested in this area.

**Comment by suhailshergill** [comment]
@ocharles understood. in that case the excerpt below (from my discussion with oleg) following up from edward's motivating example might be of interest to you:

```haskell
-- The example only makes sense with the *closed*, non-extensible set of effects. Indeed,
-- let us first remove the given signature of foo to make it somewhat
-- open (although not quite: the signature of modify makes StateT to be
-- the topmost, outer effect -- which is the limitation: I can't put more
-- effects on the top of State, only below. This is not the drawback of
-- transformers per se, only of the particular transformers library)

foo = do
  foo
  modify (1:)

arg:: [Integer]
arg = [1, 2, 3]

bar:: ((), [Integer])
bar = runState foo arg

baz:: ()
baz = fst bar
-- returns ()

qu:: [Integer]
qu = take 3 $ snd bar
-- returns [1, 1, 1]

-- Now, I add another effect, using the same foo, to test
-- extensibility. Although foo does not use the Error itself, foo can be
-- combined in the whole program with another function that does use
-- Error:

bar1 :: Either String ((), [Integer])
bar1 = runIdentity $ runErrorT $ runStateT foo arg

qu1:: [Integer]
qu1 = take 3 $ snd (either (error "error") id $ bar1)
-- diverges


-- And now qu1 diverges. This shows that the given example is irrelevant
-- for the discussion of extensible effects and modular effect libraries
-- as it is unmodular and uncomposable. It also illustrates how fragile
-- the lazy tricks are: as much as looking at the program the wrong way
-- may send it in the infinite loop.
```

**Comment by ocharles** [comment]
Very interesting, thank you!

**Comment by suhailshergill** [comment]
an update for those subscribed to this issue.
i've been able to port most of the effects (including coroutines) to the new implementation of Eff1. in addition, i have also settled on an open-union implementation which works across ghc compiler versions (the implementation internally uses `unsafeCoerce` and so i will need to add some tests for it). this is all very good news, because those were two of the biggest hurdles in incorporating ideas from the freer paper.

so, while there's still work left to do the rest should be much more straightforward. i'm looking forward to being able to make a release soon :)

**Comment by eskimor** [comment]
Yeah! :-) I am currently using the freer package for my work and I like it. Looking forward to replacing it with extensible-effects!

**Comment by fosskers** [comment]
I use `extensible-effects` in many of my projects and am always looking forward to improvements.

**Comment by suhailshergill** [comment]
a teaser of what `Reader` effect will look like in the new version: https://github.com/suhailshergill/extensible-effects/blob/sss/freer/src/Control/Eff/Reader/Strict1.hs note the lack of `Typeable` constraint :)
