### ISSUE TITLE
Please add extensible-effects to Stackage

### ISSUE THREAD

**Issue by jasonzoladz** [suhailshergill/extensible-effects#57]
`cabal install` is dead.  Long-live `stack install`!

**Comment by suhailshergill** [comment]
@jasonzoladz is hackage also long dead?

**Comment by fosskers** [comment]
Nah, `stackage` uses Hackage as a backend for special dependencies which aren't available on Stackage (which is how I get EE into my projects currently).

**Comment by suhailshergill** [comment]
hmm so can this issue be closed, or is there a benefit (for end users) to adding to stackage?

**Comment by fosskers** [comment]
It makes it easier for developers who use EE in their projects and build with `stack`. Having EE in Stackage would mean less custom configuration.

**Comment by suhailshergill** [comment]
@fosskers @jasonzoladz could either of you confirm whether or not you're able to access extensible-effects via stackage?
i believe this issue has been resolved

**Comment by jasonzoladz** [comment]
Not yet.  If you recently submitted this to Stackage, it won't make it in
until the next resolver gets released.  I'll keep an eye out for it in the
next resolver and follow up with you if it's not there.  Thanks!

**Comment by suhailshergill** [comment]
@jasonzoladz awesome. please reopen the issue if it's not there. closing this for now.
