### ISSUE TITLE
Sample on Hackage broken

### ISSUE THREAD

**Issue by eallik** [suhailshergill/extensible-effects#58]
The example at https://hackage.haskell.org/package/extensible-effects-1.11.0.0/docs/Control-Eff.html refers to the non-existent module `Control.Eff.State` and at least the non-existent function `onState`.

**Comment by suhailshergill** [comment]
@eallik thanks for the report, looking into it

**Comment by suhailshergill** [comment]
- [ ] fix the code example
- [ ] add [doctest](https://hackage.haskell.org/package/doctest) to prevent such errors in the future
