### ISSUE TITLE
MonadError, MonadThrow, MonadCatch, MonadMask instances for module Exception 

### ISSUE THREAD

**Issue by SkorikGG** [suhailshergill/extensible-effects#66]
I suggest adding implementation of the `MonadError`, `MonadThrow`, `MonadCatch`, `MonadMask` instances in the module `Control.Eff.Exception`. This will allow you to use the functions of the such modules as `Control.Monad.Catch`, for exampe `bracket`.
```
type SomeExc = Exc SomeException

runSomeExc :: Eff (SomeExc:> r) a -> Eff r (Either SomeException a)
runSomeExc = runExc

instance (Member SomeExc r) => MonadThrow (Eff r) where
    throwM = throwExc . toException

instance (Member SomeExc r) => MonadCatch (Eff r) where
    catch eff f = catchExc eff $ \e -> maybe (throwExc e) f $ fromException e

instance (Exception e,Member (Exc e) r,SetMember Exc (Exc e) r) => MonadError e (Eff r) where -- SetMember due to
    throwError = throwExc                                                                     -- functional dependency 
    catchError = catchExc                                                                     -- in MonadError

instance (Member SomeExc r) => MonadMask (Eff r) where
  mask a = a id
  uninterruptibleMask a = a id
```
It can also be useful
```
liftWithExc :: forall r m a. (Typeable m, Member SomeExc r,SetMember Lift (Lift m) r,MonadCatch m) =>
                m a -> Eff r a
liftWithExc = liftEitherM . (Control.Monad.Catch.try  :: m a -> m (Either SomeException a))
```
for making single exit point for exceptions.

**Comment by suhailshergill** [comment]
@SkorikGG could you submit a PR?

**Comment by suhailshergill** [comment]
@SkorikGG do you have an example of the kind of code you'd be able to write, which the above enables? Specifically, do you have a `bracket` example (with expected results), using the above instances? that would help me sanity-check the implementation.

**Comment by suhailshergill** [comment]
relates to #7

**Comment by suhailshergill** [comment]
@SkorikGG i was trying out the code snippet you shared, you were using `UndecidableInstances` above correct?
could you also share a snippet which made use of the instances above? thanks!

**Comment by suhailshergill** [comment]
@power-fungus @greydot ooc, what are your thoughts on above. as users of the library, do you see much utility in this?
since i've not heard from @SkorikGG , if there isn't value, i'm inclined to close this issue.

**Comment by power-fungus** [comment]
@suhailshergill I am not a heavy user of async exceptions, so I have no expert knowledge on this topic. I would suggest to close this issue and postpone this discussion to when the use of extensible effects is more clear.

Personally, I am in favor of implementing type-classes like these so that libraries can be used out-of-the-box (like MonadIO). I am aware that this adds more package dependencies simply for instanciating a typeclass. Sometime in the future, I would like to have the mtl Typeclasses - especially MonadState - so that the lens-library's (+=) operators work seamlessly using the `Eff` monad. Implementing inside a own package `extensible-effects-mtl-classes` may be a reaonable solution.

**Comment by greydot** [comment]
@suhailshergill I'm not sure this is terribly useful, given that it would require converting back and forth between SomeException and actual exception types. My needs are more or less covered by 'catchDynE' from Control.Eff.Lift here.

There are some scenarios where MonadCatch and MonadThrow would come in handy (e.g. writing servant api handlers), but not with a hardcoded exception type.

**Comment by suhailshergill** [comment]
@power-fungus i'm not that concerned about package dependencies.
love the idea of making `lens` plug and play! happy for it to be done as part of this, or as part of an independent package.

my concern in this case is one echoed by @greydot : the limited utility of having a hardcoded exceptions.

i'll close this issue for now. happy to reopen and consider a design which addresses a concrete example (we are missing one right now).
