### ISSUE TITLE
lift and bracket pattern

### ISSUE THREAD

**Issue by ibotty** [suhailshergill/extensible-effects#7]
hi,

i hope it's ok to use the issue tracker for support. 

maybe i am missing things, but how can i use `bracket`-like functions within a (lifted-IO) effect?

i'd like a function `bracket :: SetMember Lift (Lift IO) r => Eff r a -> (a -> Eff r b) -> (a -> Eff r c) -> Eff r c`, or more specific `SetMember Lift (Lift IO) r => IO a -> (a -> IO b) -> (a -> IO c) -> Eff r c`, but i could not construct it easily from `Control.Exception.bracket`. when trying to implement this `bracket` myself, i ran into problems with `mask`.

Or is the idiomatic way to use a specific effect? so you might have e.g. (not thought through) `runBracket` which will only open/close the resources and convert all the exceptions to `Control.Eff.Exception.Exc` using `throwExc` and `try`. that's nice and explicit of course, but you risk missing some exceptions and not closing the resource.

**Comment by suhailshergill** [comment]
related:
- http://okmij.org/ftp/Haskell/misc.html#catch-MonadIO
-- http://okmij.org/ftp/Haskell/extensible/EffDynCatch.hs

**Comment by suhailshergill** [comment]
@ibotty does the recent addition of `catchDynE` let you do what you'd originally wanted here? see 60850d for relevant usage examples

**Comment by ibotty** [comment]
Sorry, I missed the comment. Yes, that captures (pun intended) my intentions.
