### ISSUE TITLE
Remove usage of deprecated OverlappingInstances

### ISSUE THREAD

**Issue by suhailshergill** [suhailshergill/extensible-effects#77]
Using [`OpenUnion52.hs`](http://okmij.org/ftp/Haskell/extensible/OpenUnion52.hs) results in the following build error with `make test`

- [x] [`Test/NdetEff`](https://github.com/suhailshergill/extensible-effects/blob/master/test/Control/Eff/NdetEff/Test.hs)
```
[ 2 of 20] Compiling Control.Eff.NdetEff.Test ( test/Control/Eff/NdetEff/Test.hs, dist/build/extensible-effects-tests/extensible-effects-tests-tmp/Control/Eff/NdetEff/Test.o )

test/Control/Eff/NdetEff/Test.hs:54:53: error:
    • Couldn't match type ‘Writer [Char]’ with ‘NdetEff’
        arising from a use of ‘tsplit’
    • In the first argument of ‘runListWriter’, namely ‘tsplit’
      In the second argument of ‘($)’, namely ‘runListWriter tsplit’
      In the second argument of ‘($)’, namely
        ‘makeChoiceA $ runListWriter tsplit’
   |
54 |       tsplitr20 = run $ makeChoiceA $ runListWriter tsplit
   |                                                     ^^^^^^

test/Control/Eff/NdetEff/Test.hs:55:61: error:
    • Couldn't match type ‘Writer [Char]’ with ‘NdetEff’
        arising from a use of ‘tsplit’
    • In the first argument of ‘msplit’, namely ‘tsplit’
      In the first argument of ‘(>>=)’, namely ‘msplit tsplit’
      In the first argument of ‘runListWriter’, namely
        ‘(msplit tsplit >>= unmsplit)’
   |
55 |       tsplitr21 = run $ makeChoiceA $ runListWriter (msplit tsplit >>= unmsplit)
```

ignoring the above and continuing with the make recipe results in another compilation error further along
- [x] [`Test/Operational`](https://github.com/suhailshergill/extensible-effects/blob/master/test/Control/Eff/Operational/Test.hs)
```
[ 3 of 20] Compiling Control.Eff.Operational.Test ( test/Control/Eff/Operational/Test.hs, dist/build/extensible-effects-tests/extensible-effects-tests-tmp/Control/Eff/Operational/Test.o )

test/Control/Eff/Operational/Test.hs:25:39: error:
    • Could not deduce (Data.OpenUnion.FindElem (Program Jail) r)
        arising from a use of ‘prog’
      from the context: (Member (State [String]) r,
                         Member (Writer String) r)
        bound by the type signature for:
                   comp :: forall (r :: [* -> *]).
                           (Member (State [String]) r, Member (Writer String) r) =>
                           Eff r ()
        at test/Control/Eff/Operational/Test.hs:(22,7)-(24,25)
    • In the second argument of ‘runProgram’, namely ‘prog’
      In the expression: runProgram adventPure prog
      In an equation for ‘comp’: comp = runProgram adventPure prog
   |
25 |       comp = runProgram Eg.adventPure Eg.prog
```

ignoring above we get errors in [`Test/Lift`](https://github.com/suhailshergill/extensible-effects/blob/master/test/Control/Eff/Lift/Test.hs). there clearly are some deficiencies in the current implementation of `OpenUnion52`.

**Comment by Lysxia** [comment]
For `NdetEff.Test`, `tsplitr20` and `tsplitr21` get inferred the type `forall w. [(Integer, [w])]`. In particular, instance resolution does not unify `w` with `String`.

Here's where the error message comes from. The constraint `FindElem (Writer String) '[Writer w, NdetEff]` in the type of `tsplit` doesn't see an equality `w ~ String`, so there is only one candidate instance `FindElem t r => FindElem t (t' ': r)`, with `r ~ '[NdetEff]`, which we pick. The next instance to be picked is `{-# INCOHERENT #-} t ~ s => FindElem t '[s]`, with `t ~ Writer String`, `s ~ NdetEff`, and there we are.

One fix is to annotate the intended types for `tsplitr20` and `tsplitr21` (`[(Integer, [String])]`) (and perhaps `tsplit10` and `tsplit11` just for consistency).

Another way may be to remove the `INCOHERENT` annotation from `FindElem t (t ': r)` (only that one!). It at least helps getting better error messages for those who can read "overlapping instance" errors.

Somewhat counterintuitively, it also makes this test case compile: `tsplitr20` and `tsplitr21` get inferred `forall w. FindElem (Writer String) '[Writer w, NdetEff] => [(Integer, [w])]`, deferring resolution to the call sites (where we do have `w ~ String`). Although that might work well, this deferral is a bit unexpected.

- The intention is really for the written type `w` to be `String`; the programmer knows that at the definition of `tsplitr20`, but that doesn't seem to be the kind of thing that can easily be inferred; some explicit types would be necessary to best express that.
    A good usage pattern might be for every handler of effects with type parameters to be explicitly specialized with a type application (e.g., `runListWriter @String`).

- We still get the unhelpful "types don't match" error in case `w` is instantiated with any type that doesn't unify with `String` (i.e., not `a` or `[a]` where `a` is an uninstantiated type variable), but I'm not sure how this can be improved here anyway.

**Comment by Lysxia** [comment]
The rest of the errors seem to be of the same kind. To summarize, the following changes make all tests compile and pass:

- remove `INCOHERENT` from `instance FindElem t (t ': r)`;
- add `OVERLAPPABLE` to `instance (p ~ 'False) => EQU a b p`.

But I don't think that solves the underlying problem, which is that it is not possible to infer the effects that are handled, e.g., inferring `w` in `Writer w`. For example, if we want to run an overloaded effectful computation with a type such as `m :: Member (Writer Int) r1 => Eff r1 ()` using `runWriter`, we may intuitively expect `m` to be specialized with type `Eff '[Writer Int] ()`, but there is no way for the compiler to infer that from the expression `runWriter m` alone; `m` could just as well be of type `Eff '[Writer Bool, Writer Int] ()` (and `runWriter` would be handling a bogus `Writer Bool` effect).

Many cases (including the tests here) somehow work out because there is more context from using the results of handling these effects, but that may generally not be the case. My earlier suggestion for users to make calls to handlers monomorphic would reduce the potential for such confusion.

**Comment by suhailshergill** [comment]
@Lysxia thanks for looking into this. 
I'm on my cell right now, so apologize for the brevity but your point regarding effect inference is well made. It is a consequence of the open world assumption that `Eff` makes. I think your recommendation of making calls monomorphic (wherever applicable/possible) is worth sharing with the users as a possible pattern (and in some cases will be necessary).

**Comment by suhailshergill** [comment]
@Lysxia fyi you might be interested in 9803959 and 6c1349e (part of #80 )
