### ISSUE TITLE
Add explicit implementation for `*>` to be compatible with new `forever`

### ISSUE THREAD

**Issue by JustusAdam** [suhailshergill/extensible-effects#84]
The following code is a simple stacking of `State Int` and `Lift IO`. This is a simplification of very common pattern in applications with an event loop. 

```hs
import Control.Eff.State.Lazy
import Control.Eff.Lift
import Control.Eff

compute :: (Member (State Int) r, SetMember Lift (Lift IO) r) => Eff r ()
compute = forever $ do
  i <- get
  lift $ putStrLn $ show (i :: Int)
  modify (succ :: Int -> Int)

main = runLift $ evalState compute (0 :: Int)
```

The problem with this code is that actually, if you run it, nothing happens. 

The expected semantics would be that it starts printing out intermediate results endlessly, which it does not do. BTW the same behaviour is also observable when using `Reader` rather than `State` and now that I think of it, it probably also exhibits the same behaviour for just `Lift IO` as well.

The culprit in this case, is `forever` which is now implemented in `base` using `Applicative`.

```hs
forever     :: (Applicative f) => f a -> f b
forever a   = let a' = a *> a' in a'
```

Crucial here is that it uses `*>`, not `>>`. I have tested a custom `forever` using `>>` and that *does exhibit the desired behaviour*. 

As far as I could discern it the issue lies in the default implementation of `*>`.

```hs
(*>) :: f a -> f b -> f b
a1 *> a2 = (id <$ a1) <*> a2
```

As you can see it uses `<*>` internally which means it needs the result of `a2` before it can actually return a result. This, I think, means it has to evaluate the free monad to the right completely, which is impossible.

I think it would be a good idea to add a custom implementation for `*>` (and `<*` while we're at it) that is lazier and does not evaluate the entire monad.

**Comment by Lysxia** [comment]
This seems to be fixed in the latest version; the relevant commit is cf4cecc.

**Comment by JustusAdam** [comment]
Oh intersting. I assumed I was using a new-enough version. Nice to see it being fixed.
