### ISSUE TITLE
-Werror

### ISSUE THREAD

**Issue by greydot** [suhailshergill/extensible-effects#87]
Numerous modules in extensible-effects have -Werror enabled unconditionally. Given that there is a cabal flag for that now, maybe the pragmas in those modules should be removed?

This change will make life a bit easier when using development tools like Intero.

**Comment by suhailshergill** [comment]
@greydot good catch. Agreed. 
I'm traveling, but if you submit PR I can review

**Comment by greydot** [comment]
https://github.com/suhailshergill/extensible-effects/pull/88
